spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}275b652724ed175bf90657ef55dd506b3c25302da45a0ecac7f8d1953e11cac4'

token:
  expiration_time: 86400000
  secret: user_token_native_service_default

gateway: 
  ip: 211.174.55.156    